apiVersion: v1
data:
  database_url: bXlzcWw6Ly9yb290OnBhc3N3b3JkQGRiLXVzZXJzOjMzMDYvdXNlcnNfZGI/c2NoZW1hPXB1YmxpYw==
kind: Secret
metadata:
  creationTimestamp: "2024-07-12T22:12:32Z"
  name: ms-users-secrets
  namespace: default
  resourceVersion: "17257"
  uid: d60be206-14d8-4fcc-94d7-02b6b953e11f
type: Opaque
