apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-users
  template:
    metadata:
      labels:
        app: db-users
    spec:
      containers:
      - name: db-users
        image: mysql:8.4.1
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-users-secrets
              key: database_password
        - name: MYSQL_DATABASE
          value: "users_db"
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: users-db-pvc